package shared.data.source.ai

import kotlinx.coroutines.flow.Flow
import shared.data.source.DataSource

/**
 * Interface for interacting with AI services.
 * Provides functionality to send prompts to AI models and receive responses.
 */
interface AiSource : DataSource {

    /**
     * Sends a prompt to the AI model and returns a flow of response text.
     * The flow allows for streaming responses as they are generated by the AI.
     *
     * @param prompt The text prompt to send to the AI model.
     * @return A flow of response text from the AI model.
     */
    suspend fun reply(prompt: String): Flow<String>
}
