ktor:
    development: true
    application:
        modules:
            - kotli.app.ApplicationKt.module
    deployment:
        port: 8080
        watch:
            - classes
            - resources
